
import Providers from "@/components/Providers";
import "./globals.css";



export const metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html
      lang="en"
      className={` h-full antialiased`}
    >
      <body className="min-h-full flex flex-col"> <Providers>{children}</Providers> </body>
    </html>
  );
}
