
import Providers from "@/components/Providers";
import "./globals.css";
import Navbar from "@/components/Navbar";



export const metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html
      lang="en"
      className={` h-full antialiased`}
    >
      <body suppressHydrationWarning className="min-h-full flex flex-col">
        <Navbar/>

         <Providers>
            {children}
          </Providers> 
          
         </body>
    </html>
  );
}
